# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /mobile-api-dev

# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30 # secs

# Session Token有效时间配置(毫秒)
session:
  expirationTime: 60000

## redis configuration
#wow:
#  redis:
#    database: 0
#    host: 10.0.60.121
#    password: admin123
#    port: 6379
#    timeout: 0
#    pool:
#      max-active: 8
#      max-idle: 8
#      max-wait: -1
#      min-idle: 0

# data source configuration
spring:
  datasource:
    price:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    stock:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    page:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    product:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    order:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
    marketing:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: z123456
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 10
      maxWait: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      validationInterval: 30000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 120000
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer

#日志配置
logging:
  file: ${HOME}/ApplicationLog/mobile-api/spring-mobile-api.log
  level:
    root: INFO
    org:
      springframework:
        web: WARN

# MyBatis specifics
#mybatis:
#  typeAliasesPackage: com.wow.attribute.model,com.wow.user.model
#  mapperLocations: classpath:/mapper/attribute/*Mapper.xml,classpath:/mapper/user/*Mapper.xml

#  config：mybatis-config.xml配置文件的路径
#  typeHandlersPackage：扫描typeHandlers的包
#  checkConfigLocation：检查配置文件是否存在
#  executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE


# Security specifics