server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /user-service-test

session:
  expirationTime: 60000

spring:
  datasource:
    user:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.60.121:3388/wowdsgn?useSSL=false
      username: root
      password: z123456
      maxActive: 10
      maxIdle: 5
      minIdle: 0
      defaultAutoCommit: false